---
- name: Install system dependencies
  apt:
    name:
      - gfortran
      - libreadline-dev
      - libx11-dev
      - libxt-dev
      - libpng-dev
      - libjpeg-dev
      - libcairo2-dev
      - xvfb
      - libbz2-dev
      - libzstd-dev
      - liblzma-dev
      - libssh-dev
      - libblas-dev
      - libopenblas-dev
      - libopenblas-dev
      - liblapack-dev
      - liblapack3
      - libcurl4-openssl-dev
      - zlib1g-dev
      - texinfo
      - texlive
      - texlive-fonts-extra
      - screen
      - wget
      - libpcre2-dev
      - openjdk-11-jdk
    state: present

- name: Add Michael Rutter's apt key
  get_url:
    url: https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc
    dest: /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc

- name: Add CRAN repository into sources list
  apt_repository:
    filename: cran40
    repo: deb https://cloud.r-project.org/bin/linux/ubuntu {{ ansible_distribution_release }}-cran40/
    state: present

- name: Update apt repo and cache
  apt:
    update_cache: true

- name: Install R
  apt:
    name:
      - r-base
      - r-base-dev
    state: present

- name: Create the site-library folder
  file:
    path: /usr/lib/R/site-library/
    state: directory
    mode: "0777"
    recurse: true

- name: Create Rprofile.site file
  template:
    src: Rprofile_site.j2
    dest: /usr/lib/R/etc/Rprofile.site
    owner: root
    group: root
    mode: '0644'
    force: true

- name: Change libblas alternative to openblas
  alternatives:
    name: libblas.so.3-x86_64-linux-gnu
    path: /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3

- name: Configure Java for R
  command:
    cmd: R CMD javareconf
  changed_when: false
