---
- name: Set timeout
  lineinfile:
    path: /etc/rstudio/rserver.conf
    line: auth-timeout-minutes=240
    state: present
    create: true

- name: Allow access to /srv/shiny-server/ folder
  lineinfile:
    path: /etc/rstudio/rsession.conf
    line: directory-view-whitelist=/srv/shiny-server
    state: present
    create: true

- name: Check if default_site file exists
  stat:
    path: /etc/nginx/sites-enabled/default_site
  register: nginx_file_check

- block:
  - name: Add map to Nginx config file
    blockinfile:
      path: /etc/nginx/sites-enabled/default_site
      block: |
        map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
            }
      marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK #1 -->"
      insertbefore: BOF
    notify: restart_nginx

  - name: Configure Nginx as reverse proxy for RStudio Server
    blockinfile:
      path: /etc/nginx/sites-enabled/default_site
      block: |2
                rewrite ^/rstudio$ $scheme://$http_host/rstudio/ permanent;

                location /rstudio/ {
                        rewrite ^/rstudio/(.*)$ /$1 break;
                        proxy_pass http://localhost:8787;
                        proxy_redirect http://localhost:8787/ $scheme://$http_host/rstudio/;
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection $connection_upgrade;
                        proxy_read_timeout 20d;
                }
      marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK #3 -->"
      insertbefore: "location / {"
    notify: restart_nginx
  when: nginx_file_check.stat.exists
