---
- name: Install Basic Services and Configurations
  hosts: aws_ec2
  become: true

  vars_files:
    - vars/config_vars.yml

  pre_tasks:
    - name: Update packages
      import_role:
        name: update_packages
      tags: always

    - name: Set security configurations
      import_role:
        name: secure_server
      tags: secure

    - name: Add Swap memory
      import_role:
        name: add_swap
      tags: swap

  tasks:
    - name: Install common system dependencies
      apt:
        name:
          - openssl
          - libssl-dev
          - cmake
          - make
          - gcc
          - g++
          - git
          - gdebi-core
        state: present

    - name: Set default locale
      import_role:
        name: set_locale
      tags: locale

    - name: Create personal user
      user:
        name: "{{ personal_user }}"
        password: "{{ personal_user_password | password_hash('sha512') }}"
        update_password: on_create

    - name: Add sudo rights for personal user
      lineinfile:
        dest: /etc/sudoers
        regexp: '^{{ personal_user }}'
        line: '{{ personal_user }} ALL=(ALL) NOPASSWD: ALL'
        state: present
        validate: 'visudo -cf %s'

    - name: Install and configure Nginx
      import_role:
        name: install_nginx
      tags: nginx

    - name: Install and configure Postgresql
      import_role:
        name: install_postgresql
      tags: postgresql

    - name: Install R
      import_role:
        name: install_r
      tags: r
