---
- name: Install and Configure RStudio Server
  hosts: aws_ec2
  become: true

  vars_files:
    - vars/config_vars.yml

  tasks:
    - name: Install RStudio server
      import_role:
        name: install_rstudio
      tags: rstudio

    - name: Configure RStudio
      import_role:
        name: configure_rstudio
      tags: configure_rstudio
