---
- name: Install language pack
  apt:
    name: "{{ language_pack }}"
    state: present

- name: Ensure the locale exists
  locale_gen:
    name: "{{ default_locale }}"
    state: present

- name: Get current locale configuration
  command: localectl status
  register: locale_status
  changed_when: false

- name: Parse 'LANG' from current locale and language configuration
  set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

- name: Set the default locale
  command: |
    localectl set-locale LANG={{ default_locale }}
  changed_when: locale_lang != default_locale
