---
- name: Create shiny-apps group
  group:
    name: shiny-apps

- name: Add the main users to the shiny-apps group
  user:
    name: "{{ item }}"
    append: true
    groups:
      - shiny-apps
  with_items:
    - shiny
    - "{{ personal_user }}"
    - "{{ ansible_user }}"

- name: Configure /srv/shiny-server folder
  file:
    path: /srv/shiny-server
    state: directory
    owner: "{{ personal_user }}"
    group: shiny-apps
    mode: "0777"

- name: Check if default_site file exists
  stat:
    path: /etc/nginx/sites-enabled/default_site
  register: nginx_file_check

- block:
  - name: Add map to Nginx config file
    blockinfile:
      path: /etc/nginx/sites-enabled/default_site
      block: |2
        map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
        }
      marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK #1 -->"
      insertbefore: BOF
    notify: restart_nginx

  - name: Configure Nginx as reverse proxy for shiny-server
    blockinfile:
      path: /etc/nginx/sites-enabled/default_site
      block: |2
            rewrite ^/shiny$ $scheme://$http_host/shiny/ permanent;

            location /shiny/ {
                rewrite ^/shiny/(.*)$ /$1 break;
                proxy_pass http://localhost:3838;
                proxy_redirect / $scheme://$http_host/shiny/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_read_timeout 20d;
                proxy_buffering off;
            }
      marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK #2 -->"
      insertafter: "server_name _;"
    notify: restart_nginx
  when: nginx_file_check.stat.exists
