---
- name: Install Nginx and PHP packages
  apt:
    name:
      - nginx
      - php-fpm
    state: latest

- name: "Update installed packages"
  package_facts:
    manager: "apt"

- name: Create html directory
  file:
    path: /var/www/html
    owner: "{{ ansible_user }}"
    group: www-data
    mode: '0770'
    state: directory

- name: Get PHP major version
  set_fact:
    php_major_version: "{{ ansible_facts.packages['php-fpm'][0].version |
         regex_search('(?<=\\d:)\\d\\.\\d', multiline=True) | trim }}"

- name: Remove default sites file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart_nginx

- name: Create Nginx sites configuration file
  template:
    src: default_site.j2
    dest: /etc/nginx/sites-enabled/default_site
    owner: root
    group: root
    mode: '0644'
    force: false
  notify: restart_nginx

- name: Increase max file upload size
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "client_max_body_size"
    line: "\tclient_max_body_size 1000M;"
    insertafter: "http {"
    state: present
  notify: restart_nginx
