---
- name: Addthe GPG signing key for the PostgreSQL repository
  get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /etc/apt/trusted.gpg.d/postgresql_ubuntu_key.asc

- name: Add PostgreSQL repository
  apt_repository:
    filename: pgdg
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present

- name: Update apt repo and cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install PostgreSQL libraries
  apt:
    name:
      - gnupg2
      - libpq-dev
      - postgresql
      - postgresql-client
      - postgresql-client-common
      - unixodbc-dev
      - odbc-postgresql
      - python3-psycopg2
    state: present

- name: "Update installed packages"
  package_facts:
    manager: "apt"

- name: Get PostgreSQL major version
  set_fact:
    postgresql_major: "{{ ansible_facts.packages['postgresql'][0].version\n
    | regex_search('^\\d{2}', multiline=True) | trim }}"

- name: Configure PostgreSQL access rules
  postgresql_pg_hba:
    dest: /etc/postgresql/{{ postgresql_major }}/main/pg_hba.conf
    contype: "{{ item.contype }}"
    users: "{{ item.users }}"
    address: "{{ item.address }}"
    databases: all
    method: "{{ item.method }}"
  with_items: "{{ postgresql_rules }}"
  notify: restart_postgresql

- name: Force restart_postgresql handler
  meta: flush_handlers

- name: Configure PostgreSQL options
  postgresql_set:
    name: listen_addresses
    value: '*'
  notify: restart_postgresql

- name: Force restart_postgresql handler
  meta: flush_handlers

- name: Create the main PostgreSQL user
  postgresql_user:
    name: "{{ ansible_user }}"
    password: "{{ postgres_password }}"
    role_attr_flags: CREATEDB,CREATEROLE,SUPERUSER
    state: present

- name: Create database for the main user
  postgresql_db:
    name: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    state: present
